name: Sync to Hugging Face Space

on:
  push:
    tags:
      - v*
  workflow_dispatch:

concurrency:
  group: hf-sync-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  sync:
    name: sync
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    environment: production-hf-space

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          lfs: true
          persist-credentials: false
      - name: Sync GitHub to Hugging Face Hub
        uses: huggingface/hub-sync@da166beda9a9aff15d1de9a82c6dc86c410ea3ee  # v0.2.1
        with:
          github_repo_id: pollen-robotics/reachy_mini_conversation_app
          huggingface_repo_id: pollen-robotics/reachy_mini_conversation_app
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: space
          space_sdk: static
